### ISSUE TITLE
IPython shell segfault on tab completion

### ISSUE THREAD

**Issue by simonbyrne** [JuliaPy/pyjulia#132] opened 2017-11-08 21:31 UTC
In the ipython shell:
```
import julia
j = julia.Julia()
j.<tab>
```
immediately segfaults.

On OS X:
```
Python 3.6.3 (default, Oct  4 2017, 06:09:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by simonbyrne** [comment] 2017-11-14 21:38
Interestingly, it's fine in the normal python3 shell. So maybe it's an IPython issue?

**Comment by stevengj** [comment] 2017-11-14 21:58
IPython does tab completion differently than python3, but it's probably ultimately a pyjulia bug that is being triggered.

**Comment by zsunberg** [comment] 2017-11-28 18:20
On linux with ipython 5.1.0, I am able to do tab completion of methods of the Julia object, but when I try to complete filenames in a string, it segfaults, e.g.
```
In [1]: import julia

In [2]: j = julia.Julia()

In [3]: j.evalfile("new<tab>
signal (11): Segmentation fault                                               
while loading no file, in expression starting on line 0                       
Segmentation fault
```

**Comment by tkf** [comment] 2018-05-13 06:49
As @takluyver guessed in https://github.com/ipython/ipython/issues/10899#issuecomment-344541306, it looks like threading problem.  Just in case if someone wants to reproduce the problem in a script, here it is:

```python
import threading

from IPython.testing.globalipapp import get_ipython
from julia import Julia

ip = get_ipython()
ip.user_ns['julia'] = Julia()


def ip_complete():
    print(ip.complete('julia.sin.'))


print("ip_complete() in main thread:")
ip_complete()
print()

print("ip_complete() in different thread:")
th = threading.Thread(target=ip_complete)
th.start()
th.join()
```

It prints

```
ip_complete() in main thread:
('julia.sin.', ['julia.sin.jl_value'])

ip_complete() in different thread:

signal (11): Segmentation fault
```

I wonder if PyCall/libjulia can support multi-thread usage. https://github.com/JuliaLang/julia/issues/17573

**Comment by tkf** [comment] 2018-05-13 07:04
Of course, producing segfault this way doesn't require IPython:

```python
import threading

from julia import Julia

j = Julia()
j_sin = j.sin


def access_julia():
    j_sin.jl_value


th = threading.Thread(target=access_julia)
th.start()
th.join()
```

**Comment by takluyver** [comment] 2018-05-20 11:25
When prompt_toolkit version 2 is ready, we (IPython) should be able to do completions in the main thread, which should avoid this kind of issue. A few things have come up that don't like their completions running from another thread.

**Comment by tkf** [comment] 2018-07-31 16:50
I just found out that IPython master (to be released as 7.0) already was upgraded to use prompt_toolkit 2.0! https://github.com/ipython/ipython/pull/11177  I have to try it soon...

FYI, here is IPython's 7.0 milestone https://github.com/ipython/ipython/milestone/43

**Comment by tkf** [comment] 2018-07-31 22:38
Yes, tab completion in IPython master works with pyjulia!

![image](https://user-images.githubusercontent.com/29282/43490988-a6374234-94d7-11e8-96c0-717ad613bcb3.png)

**Comment by tkf** [comment] 2018-10-20 03:02
IPython 7.0 is already released and available in PyPI and Anaconda.  Closing...

**Closed by tkf** 2018-10-20 03:02 UTC
