### ISSUE TITLE
WindowsError "The specified procedure could not be found" on initializing pyjulia object

### ISSUE THREAD

**Issue by pennib** [JuliaPy/pyjulia#67] opened 2016-10-17 23:48 UTC
Hi,

I am having an issue starting pyjulia on Windows 10. When I run 

j = julia.Julia() 

I receive the following dialog saying:

The procedure entry point _ZSt24_throw_out_of_range_fmtPKcz could not be located in the dynamic link library C:...\Julia-0.5.0\bin\LLVM-3.7.dll

This is followed by another dialog with the same message regarding libjulia.dll

I am using Version 0.5.0 (2016-09-19 18:14 UTC  |  x86_64-w64-mingw32    of Julia.

I believe I have followed your installation instructions .For installing PyCall, I set the python environment to '' and PyCall downloaded a conda installation. It may have downloaded a 32 bit version of python. 

Thanks for your help in advance.

**Comment by tkf** [comment] 2018-11-16 23:44
I'm closing it since this issue is old.  Newer versions of PyJulia/Julia/Python may solve it.  Please reopen if you still have the issue.

**Comment by jjhartmann** [comment] 2018-12-07 20:38
I'm also seeing this issue with Julia 1.0.2. 

When I try to import `from julia import Main`,  I get an "Entry Point Not Found" Error. 

```
The procedure entry point _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE could not be located in the dynamic link library  ...\Julia-1.0.2\bin\LLVM.dll
```

Any ideas?

**Comment by tkf** [comment] 2018-12-08 01:55
Maybe https://github.com/JuliaPy/pyjulia#error-due-to-libstdc-version

**Comment by darrencl** [comment] 2019-04-05 04:15
Hi, I am getting this error also on calling `j = Julia()`.

Below is the trace:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-19-dc0e1c5f76f1> in <module>
      3 
      4 # Load TriMRS
----> 5 j = Julia()
      6 j.include("../TriMRS.jl/src/TriMRS.jl")
      7 

~\AppData\Roaming\Python\Python37\site-packages\julia\core.py in __init__(self, *args, **kwargs)
    795 
    796     def __init__(self, *args, **kwargs):
--> 797         self.__julia = Julia(*args, **kwargs)
    798     __init__.__doc__ = Julia.__init__.__doc__
    799 

~\AppData\Roaming\Python\Python37\site-packages\julia\core.py in __init__(self, init_julia, jl_init_path, runtime, jl_runtime_path, debug)
    527                 libjulia_path = libjulia_path.encode("ascii")
    528 
--> 529             self.api = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)
    530             if not jl_init_path:
    531                 if jl_runtime_path:

c:\users\tdlukas\appdata\local\programs\python\python37\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354 
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: [WinError 127] The specified procedure could not be found
```

I ran this on `jupyter notebook` (`IPython`).

**Comment by tkf** [comment] 2019-04-05 04:29
It's https://pyjulia.readthedocs.io/en/latest/troubleshooting.html#error-due-to-libstdc-version

Unfortunately I can't help for Windows problem...  What you have to do is to figure out `libjulia_path` in Julia

```julia
julia> Libdl.dlpath(string("lib", splitext(Base.julia_exename())[1]))
"/PATH/TO/LIBJULIA"
```

and then _somehow_ make the following work in (I)Python

```python
>>> import ctypes
>>> libjulia_path = "/PATH/TO/LIBJULIA"
>>> ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)
```

**Comment by davidj411** [comment] 2019-04-05 22:02
+1 Windows 10
python 3.5

followed those last steps above , same error below. 
`OSError: [WinError 127] The specified procedure could not be found`

**Comment by tkf** [comment] 2019-04-05 22:20
In general, clarifying the following points (and more, if you can think about something relevant) may help someone to investigate this more:

* Windows version (?)
* Python version: output of `python --version`, 32 or 64 bit, installation method (official? conda?, something else?)
* Julia version: output of `versioninfo()` in Julia REPL, 32 or 64 bit
* The value of `libjulia_path`
* What happend when you try to build PyCall with the Python executable you are using? What is in the log file at `C:\Users\<USERNAME>\.julia\packages\PyCall\<slug>\deps\build.log`? See, e.g.,  https://github.com/JuliaPy/pyjulia/issues/267#issuecomment-480123140

(@davidj411 you specified some of them but I think other information can be helpful)

**Comment by darrencl** [comment] 2019-04-07 23:24
Hi, I have solved the issue in `IPython` - it was `RuntimeError: It seems your Julia and PyJulia setup are not supported.` issue where the python path supplied is not lowercase. However, it shows different message in `jupyter notebook` for some reason (I did not install the notebook via anaconda, so it should use the same python backend, right?). Anyway, this also solved the issue in jupyter notebook. :)

Use this to ensure lowercase when adding python path in `julia`.

```
ENV["PYTHON"] = lowercase("PATH/TO/PYTHON")
using Pkg
Pkg.build("PyCall")
```

**Comment by tkf** [comment] 2019-04-08 00:55
> issue where the python path supplied is not lowercase

FYI that's #231 and fixed by #250. This is an issue only in PyJulia 0.2.

**Comment by darrencl** [comment] 2019-04-08 01:22
Right, I installed the `PyJulia` via `pip`, but how come I did not get the latest version?

**Comment by tkf** [comment] 2019-04-08 02:21
You can install PyJulia from `master` branch by

```
python3 -m pip install --user 'https://github.com/JuliaPy/pyjulia/archive/master.zip#egg=julia'
```

See also https://pyjulia.readthedocs.io/en/latest/installation.html#step-2-install-pyjulia

**Comment by Skoricius** [comment] 2019-05-27 19:21
Hi, I had the same issue on Windows 10 with Python 3.6 and Julia 1.1.1
There seems to be an error with libjulia.dll depending on some other libraries or files in its directory. I haven't spent time figuring out exactly what the issue is, but what fixed it for me is temporarily moving to libjulia_path directory by changing libjulia.py on line 213:

`self.libjulia = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)`

to
```
cwd = os.getcwd() 
os.chdir(os.path.dirname(libjulia_path)) 
self.libjulia = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL) 
os.chdir(cwd)
```
It's a bit hacky and I'm sure there is a better way of doing this, but seems to fix the problem.

**Comment by tkf** [comment] 2019-05-27 21:26
Thanks.  That's interesting.  Is `libjulia_path` an absolute path?  Do you have `julia` executable in your PATH (check `os.environ["PATH"]` in Python)?

**Comment by Skoricius** [comment] 2019-05-28 17:35
Yes, `libjulia_path` is an absolute path and Julia executable is on the path...
It's a bit strange because I wasn't able to reproduce the issue on another computer with the same version of Julia, Python and PyJulia. So it probably has to do something with how python environment is set up

**Comment by tkf** [comment] 2019-05-28 20:18
Yeah, that's very strange...

> how python environment is set up

My guess is this is more like a DLL-related OS-specific thing.  So maybe looking into something like https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order would help.

**Comment by AHo94** [comment] 2019-06-12 21:04
I also have the problem with the error
```
OSError: [WinError 127] The specified procedure could not be found
```
I have tried to find this libjulia.py file that @Skoricius mentioned, but I am unable to locate it.
Some info:
- I am using Windows 10
- Using the official Python3.7 that is 32 bit
- Julia version 1.1.1 also 32 bit
- The build.log file is empty after doing the PyCall example

**Comment by Skoricius** [comment] 2019-06-13 10:49
Depending on the version of julia python package, I believe the file could also be core.py located at ~\AppData\Local\Programs\Python\Python36\Lib\site-packages\julia\core.py on my system, and the line in question is 684

**Comment by lschmelting** [comment] 2019-06-18 13:01
@AHo94 Just as another example: The file is C:\Users\<Username>\Miniconda3\Lib\site-packages\julia\core.py on my system.

**Comment by lschmelting** [comment] 2019-06-18 13:29
> 
> 
> It's https://pyjulia.readthedocs.io/en/latest/troubleshooting.html#error-due-to-libstdc-version
> 
> Unfortunately I can't help Windows problem... What you have to do is to figure out `libjulia_path` in Julia
> 
> ```julia
> julia> Libdl.dlpath(string("lib", splitext(Base.julia_exename())[1]))
> "/PATH/TO/LIBJULIA"
> ```
> 
> and then _somehow_ make the following work in (I)Python
> 
> ```python
> >>> import ctypes
> >>> libjulia_path = "/PATH/TO/LIBJULIA"
> >>> ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)
> ```
Results in "process entry point "\PATH\TO\JULIA\Julia-1.1.1\bin\LLVM.dll" not found on my machine. _But only in Pycharm. Works fine in Minicondas python console_

**Comment by lschmelting** [comment] 2019-07-04 09:15
Hi, like @Skoricius I'm on  Windows 10 with Anaconda (Python 3.6.8) and Julia 1.1.1 and want to report that his fix
> ...but what fixed it for me is temporarily moving to libjulia_path directory by changing libjulia.py on line 213:
> 
> `self.libjulia = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)`
> 
> to
> 
> ```
> cwd = os.getcwd() 
> os.chdir(os.path.dirname(libjulia_path)) 
> self.libjulia = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL) 
> os.chdir(cwd)
> ```
 worked for me partially:

Error in Pycharm: 
OSError: [WinError 127] The specified procedure could not be found.
Error in Spyder:
Procedure entry point "_ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE" was not found in DLL "C:\Users\<Username>\AppData\Local\Julia-1.1.1\bin\LLVM.dll"

Since applying his fix, i can now use Julia without problems in Spyder, but not in Pycharm.

**Comment by achintamiri** [comment] 2019-09-16 14:08
Hi 
I was  facing the issue "**OSError: [WinError 127] The specified procedure could not be found** " 

I did the following steps and it worked for me on the python terminal as well as IDE (Pycharm)
I am using the latest stable Julia package available till date.

1>ENV["PYTHON"] = lowercase("PATH/TO/PYTHON")
using Pkg
Pkg.build("PyCall")

2>C:\Users<Username>\Anaconda3\Lib\site-packages\julia\core.py
Modified Line : 684

Added this 
#self.libjulia = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)
        cwd = os.getcwd() 
        os.chdir(os.path.dirname(libjulia_path)) 
        self.libjulia = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL) 
        os.chdir(cwd)
        setup_libjulia(self.libjulia)

I was able to run my julia script in Python.

This is the temporary solution but Julia packages should be updated in the build version for the permanent fix on Windows

**Comment by tkf** [comment] 2019-09-16 18:29
OK. This workaround seems to help several people so I think it is worth having it by default. I'd appreciate it if someone can create a PR to do it.

**Closed** 2019-09-17 03:38 UTC

**Comment by tkf** [comment] 2019-10-25 23:32
I have to release it.
