### ISSUE TITLE
Problem installing?

### ISSUE THREAD

**Issue by AjayTalati** [JuliaPy/pyjulia#87] opened 2017-03-07 03:16 UTC
Hi I get the following error (even though the unit tests work), when trying to install,

```
(pyphi) ajay@ajay-h8-1170uk:~/Downloads/pyjulia$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.4/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python3.4/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() missing 1 required positional argument: 'name'
(pyphi) ajay@ajay-h8-1170uk:~/Downloads/pyjulia$ 
```

Any idea how to get it working? Thanks, Ajay

**Comment by AjayTalati** [comment] 2017-03-07 03:31
Well I install `julia` using `pip`, and set my  `JULIA_HOME` path, now I get the following error?

```
>>> import julia
>>> j = julia.Julia()
ERROR: UndefVarError: dlpath not defined
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
Traceback (most recent call last):
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/site-packages/julia/core.py", line 238, in __init__
    """])
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['julia', '-e', '\n                     println(JULIA_HOME)\n                     println(Sys.dlpath(dlopen("libjulia")))\n                     ']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ajay/anaconda3/envs/pyphi/lib/python3.6/site-packages/julia/core.py", line 244, in __init__
    raise JuliaError('error starting up the Julia process')
julia.core.JuliaError: error starting up the Julia process
```

**Comment by ExpandingMan** [comment] 2017-03-16 15:20
I'm getting this also.  I fixed it at some point in the past but I can't remember what I did.

**Comment by AjayTalati** [comment] 2017-03-16 15:32
I never managed to fix it - gave up in the end, and did what I had to in `R` and python :-1: 

Be nice if someone did find a solution though?

**Comment by ExpandingMan** [comment] 2017-03-16 15:43
Yeah, it is really bad for Julia that this package is so poorly maintained.  I use Julia whenever possible, and I've found PyCall to be foolproof, pretty much everyone around me insists on using Python so sometimes I really need this thing working.

**Comment by ExpandingMan** [comment] 2017-03-16 16:23
Ok, I think the problem is that pyjulia always needs to be installed *after* PyCall is built.  And, because `pip` does all sorts of weird shenanigans, doing a `pip3 uninstall julia` and then `pip3 install julia` won't necessarily work.  I *think* what happens is that pip keeps a cache somewhere and re-installs from that unless you do things just right.  Try doing a `pip3 install -e julia` from the directory containing pyjulia.  Running the setup file with the install command might work the same way, what I really hate about that though is then the only way to uninstall is to actually hunt down the files.  (I kind of hate how python packages work to be honest.  It's ok if you have a standalone python installation, but if you are using the python that is part of your OS it is a huge pain in the ass.)

You might also want to try running from the directory which contains the pyjulia directory (not from within the pyjulia directory).

Yeah, this package is in desperate need of maintenance.  Wish I could help but it would take me a long time to figure this stuff out.  Hopefully somebody who does know what they're doing will come along and give this some much-needed attention.

**Comment by tkelman** [comment] 2017-03-18 05:02
> Well I installed the package `julia` using `pip`

How exactly? I think what's on pypi under `julia` is something different.

**Comment by ExpandingMan** [comment] 2017-03-20 13:27
Pip works for any package that has a valid `setup.py`, it doesn't have to be on PyPl.  I usually default to this rather than just running the `setup.py` script, because it gives me the comfort of, at least in principle, having an "uninstall" option (though what exactly this does is not entirely clear to me, I'm pretty sure it's not quite what it's "supposed" to do).  It is also useful to use the `pip install -e` option, which just softlinks to the directory you're installing from, rather than making copies, so it respects changes.

**Comment by Keno** [comment] 2017-07-28 18:49
Could you try #77? I've verified that `pip install ./pyjulia` installs me a working copy of pyjulia afterwards.

**Comment by tkf** [comment] 2018-11-16 23:48
I'm closing it since this issue is old.  Newer versions of PyJulia/Julia/Python may solve it.  Please reopen if you still have the issue.

**Closed by tkf** 2018-11-16 23:48 UTC
