### ISSUE TITLE
What does this error exactly mean???

### ISSUE THREAD

**Issue by karanaggarwal1994** [JuliaPy/pyjulia#84] opened 2017-02-28 13:49 UTC
```
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f20c343d51d)
Allocations: 14513031 (Pool: 14512010; Big: 1021); GC: 10
Segmentation fault (core dumped)

```

**Comment by yuyichao** [comment] 2017-02-28 13:51
It means you should post how did you get it.

**Comment by karanaggarwal1994** [comment] 2017-03-01 04:38
@yuyichao https://github.com/JuliaPy/PyCall.jl/issues/369

**Comment by karanaggarwal1994** [comment] 2017-03-01 04:54
Python code

```
jl = julia.Julia()
fn = sys.argv[1]
cap = cv2.VideoCapture(fn)
ret, frame = cap.read()
rows = frame.shape[0]
cols = frame.shape[1]
harris_cor1 = jl.eval("include(\"harris_naive.jl\")")
while true:
    res=harris_cor1(frame,rows,cols)
    ret, frame = cap.read()
```

Error Reported
```
signal (11): Segmentation fault
while loading no file, in expression starting on line 0
unknown function (ip: 0x7f20c343d51d)
Allocations: 14513031 (Pool: 14512010; Big: 1021); GC: 10
Segmentation fault (core dumped)
```

But if the code is
```
jl = julia.Julia()
fn = sys.argv[1]
cap = cv2.VideoCapture(fn)
ret, frame = cap.read()
rows = frame.shape[0]
cols = frame.shape[1]
res=harris_cor1(frame,rows,cols) #-----------------------------Adding this code
harris_cor1 = jl.eval("include(\"harris_naive.jl\")")
while true:
    res=harris_cor1(frame,rows,cols)
    ret, frame = cap.read()
```

There is no error.

Also if I edit the harris_naive.jl file and add @parallel in for loops then neither of them works. When same code I am using in julia prompt everything works fine with @parallel .

harris_naive.jl file just returns the same frame that it receives without any modification.

harris_naive.jl
```
function harris_naive_cm(fr,rows,cols)
	return fr
end
```

**Comment by stevengj** [comment] 2017-03-01 13:17
Duplicate of JuliaPy/PyCall.jl#368 ... please don't post the same issue in multiple places.

**Closed by stevengj** 2017-03-01 13:17 UTC
